name: Deploy-Test

on:
  workflow_dispatch:
    inputs:
      build-run-id:
        required: true
        type: string

jobs:
    deploy-webapp:
        uses: ./.github/workflows/reusable-deploy-webapp.yml
        with:
            build-run-id: ${{ inputs.build-run-id }}
            environment: test
        secrets: 
            GH_PAT_ACTIONS_READONLY: ${{ secrets.GH_PAT_ACTIONS_READONLY }}